### PR TITLE
Remove remaining OS/community stuff

### PR DESCRIPTION
**Pull request by hasancelik**
with the 5.13 release, the operator will become EE and closed source.

Changes:

- Remove Community Support 
- Remove EE badges
- Remove wrong helm chart repo link

### CODE REVIEW

**Comment by hasancelik** [comment]
@oliverhowell can we remove this section from older releases also?

**Comment by rebekah-lawrence** [comment]
@oliverhowell we also need to think about how to mark the whole of Operator as EE from 5.13 - it will become confusing otherwise as some topics (for example, [Persistence, Backup and Restore](https://docs.hazelcast.com/operator/5.12/backup-restore)) are explicitly marked as Enterprise already. Potentially also a badge or something to highlight it from the docs home page?

Assuming that previous versions remain available to OS, I don't think we need to remove the Community Support section from those versions (my tuppence-worth).

**Comment by hasancelik** [comment]
@rebekah-lawrence @oliverhowell 

> (for example, [Persistence, Backup and Restore](https://docs.hazelcast.com/operator/5.12/backup-restore)) are explicitly marked as Enterprise already.

We c[leaned up OS related stuff from the doc](https://github.com/hazelcast/hazelcast-platform-operator-docs/pull/212) but we forgot those badges, I will update this PR to remove them. We have already remove them from tutorial.

> we also need to think about how to mark the whole of Operator as EE from 5.13

I am open to any advice 🙂 

> Assuming that previous versions remain available to OS, I don't think we need to remove the Community Support section from those versions (my tuppence-worth).

👍

**Comment by rebekah-lawrence** [comment]
Thank you @hasan, responsive and proactive as always! 

Perhaps a line added to the end of the :description: in the index.adoc, something like "From 5.13, Hazelcast Operator requires an Enterprise license."?

The rest of the issue around this change is probably not something you can address, a strategy is needed that can be applied to the docs in these circumstances.

**Review by kutluhanmetin — APPROVED** [review]
looks good, I just made a tiny commit: https://github.com/hazelcast/hazelcast-platform-operator-docs/pull/225/commits/30e60e1506d82e2072a7db3cdb33e997094144cb

**Comment by hasancelik** [comment]
@rebekah-lawrence 

Actually, my plan is to prepare a `What's New` page as we did for Platform side:
https://docs.hazelcast.com/hazelcast/latest/whats-new
Then I will mention this EE only operator saga at there

**Comment by rebekah-lawrence** [comment]
Perfect, I should have known you'd have it in hand!

**Review by rebekah-lawrence — APPROVED** [review]
LGTM

**Pull request merged**
