### PR TITLE
use invulnerable hz and mc version

### PR DESCRIPTION
**Pull request by hasancelik**
backport of #13

### CODE REVIEW

**Review by JakeSCahill — CHANGES_REQUESTED** [review]
See #13

**Comment by JakeSCahill** [comment]
We can close this one and #14

**Comment by hasancelik** [comment]
@JakeSCahill 
> We can close this one and #14

What do you mean by closing? merging?

**Comment by JakeSCahill** [comment]
That's an old comments before we discussed adding a code comment to clarify the purpose of those attributes 😄 

This PR just needs to include the same content as #13 , then we can merge.

**Comment by hasancelik** [comment]
@JakeSCahill I have already answered your question at https://github.com/hazelcast/hazelcast-platform-operator-docs/pull/13#issuecomment-1016246063 🙂

**Review by JakeSCahill — APPROVED** [review]

**Pull request merged**
