### PR TITLE
Fixed examples in scheduling-configuration page

### PR DESCRIPTION
**Pull request by chobostar**
- fixed wrong indent in pod-antiffity

- fixed topology spread to as docs:
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
```
whenUnsatisfiable indicates how to deal with a Pod if it doesn't satisfy the spread constraint:
- DoNotSchedule (default) tells the scheduler not to schedule it.
- ScheduleAnyway tells the scheduler to still schedule it while prioritizing nodes that minimize the skew.
``` 

```
$ k explain hazelcast.spec.scheduling.topologySpreadConstraints.labelSelector
KIND:     Hazelcast
VERSION:  hazelcast.com/v1alpha1

RESOURCE: labelSelector <Object>

DESCRIPTION:
     LabelSelector is used to find matching pods. Pods that match this label
     selector are counted to determine the number of pods in their corresponding
     topology domain.

FIELDS:
   matchExpressions	<[]Object>
     matchExpressions is a list of label selector requirements. The requirements
     are ANDed.

   matchLabels	<map[string]string>
     matchLabels is a map of {key,value} pairs. A single {key,value} in the
     matchLabels map is equivalent to an element of matchExpressions, whose key
     field is "key", the operator is "In", and the values array contains only
     "value". The requirements are ANDed.
```

### CODE REVIEW

**Review by hasancelik — APPROVED** [review]
@chobostar Thanks for the PR 💯 

LGTM 👍 @JakeSCahill could you review it?

**Review by JakeSCahill — APPROVED** [review]

**Comment by hasancelik** [comment]
@chobostar Could you check @JakeSCahill's comment and resolve conflicts?

**Comment by chobostar** [comment]
@hasancelik yes, I have just checked again

Yaml files are included into adoc as is:
https://github.com/hazelcast/hazelcast-platform-operator-docs/pull/7/files#diff-76bc1e26c86f00d6cc19714cd56c2364d216a8c049aee1a6380bcb52dde1f7c7R43

Files were added manually by hand. I don't see any automation there. Thus fix the yaml file means fix the rendered doc.

**Comment by chobostar** [comment]
Here are fixed examples:
https://deploy-preview-41--pedantic-goldberg-f76ec1.netlify.app/operator/latest-snapshot/scheduling-configuration.html#pod-affinity-and-pod-anti-affinity

https://deploy-preview-41--pedantic-goldberg-f76ec1.netlify.app/operator/latest-snapshot/scheduling-configuration.html#topology-spread-constraints

As far as I see everything as expected.

**Comment by JakeSCahill** [comment]
`corev1.DoNotSchedule` became `DoNotSchedule`. Does this affect the API reference here? https://deploy-preview-41--pedantic-goldberg-f76ec1.netlify.app/operator/latest-snapshot/api-ref.html#schedulingconfiguration

**Comment by chobostar** [comment]
> `corev1.DoNotSchedule` became `DoNotSchedule`. Does this affect the API reference here? https://deploy-preview-41--pedantic-goldberg-f76ec1.netlify.app/operator/latest-snapshot/api-ref.html#schedulingconfiguration

Thanks for clarifying!

That was just typo in example yaml.

Nothing changed in API, so we don't need to change API ref.

---
There are CRD part connected with that commit:
https://github.com/hazelcast/hazelcast-platform-operator/blob/main/bundle.yaml#L937-L1033
as I see the schema exactly the same as fixed version of our example yaml.

And here
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#topologyspreadconstraint-v1-core
```
WhenUnsatisfiable indicates how to deal with a pod if it doesn't satisfy the spread constraint. - DoNotSchedule (default) 
```
also everything is consistent

**Comment by JakeSCahill** [comment]
Looks good 👌

**Comment by chobostar** [comment]
> @chobostar Could you check @JakeSCahill's comment and resolve conflicts?

@hasancelik we are done here and ready to be merged.

**Comment by hasancelik** [comment]
@chobostar Thanks a lot 👍

**Pull request merged**
